### ISSUE TITLE
Doesn't gracefully fail when compass isn't installed.

### ISSUE THREAD

**Issue by crewshin** [nathggns/node-compass#34]
This bad boy doesn't gracefully fail when compass isn't installed. Something to consider re-working.

**Comment by benoitguigal** [comment]
+1 for this issue. When compass is not installed, node crash and throw this exception which does not help a lot
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn compass ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
```
